In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

pd.set_option("display.max_columns", None)

In [2]:
PROJECT_ROOT = Path(
    r"C:\Users\Adity\OneDrive\Desktop\RESEARCH\Project Work\Inflation-Forecasting-Dashboard"
)

RAW_CPI = PROJECT_ROOT / "data" / "raw" / "cpi"
RAW_WPI = PROJECT_ROOT / "data" / "raw" / "wpi"
RAW_PPI = PROJECT_ROOT / "data" / "raw" / "ppi"

PROCESSED = PROJECT_ROOT / "data" / "processed"

PROCESSED.mkdir(parents=True, exist_ok=True)

print("Project:", PROJECT_ROOT)
print("Processed:", PROCESSED)

Project: C:\Users\Adity\OneDrive\Desktop\RESEARCH\Project Work\Inflation-Forecasting-Dashboard
Processed: C:\Users\Adity\OneDrive\Desktop\RESEARCH\Project Work\Inflation-Forecasting-Dashboard\data\processed

In [4]:
cpi_hist = pd.read_csv(
    RAW_CPI / r"C:\Users\Adity\OneDrive\Desktop\RESEARCH\Project Work\Inflation-Forecasting-Dashboard\cpi_combined_historical_2012base.csv"
)

print(cpi_hist.shape)
display(cpi_hist.head())

(156, 12)

,baseyear,year,month_code,month,state,sector,group,subgroup,index,inflation,status,value
0,2012,2025,12,December,All India,Combined,General,General-Overall,198.0,1.33,F,198.0
1,2012,2025,11,November,All India,Combined,General,General-Overall,197.9,0.71,F,197.9
2,2012,2025,10,October,All India,Combined,General,General-Overall,197.3,0.25,F,197.3
3,2012,2025,9,September,All India,Combined,General,General-Overall,197.0,1.44,F,197.0
4,2012,2025,8,August,All India,Combined,General,General-Overall,197.0,2.07,F,197.0

In [5]:
cpi_hist["date"] = pd.to_datetime(
    cpi_hist["year"].astype(str)
    + "-"
    + cpi_hist["month_code"].astype(str)
    + "-01"
)

cpi_hist = (
    cpi_hist
    .sort_values("date")
    .reset_index(drop=True)
)

In [6]:
cpi_hist = cpi_hist[
    ["date", "index"]
].rename(
    columns={
        "index": "cpi_combined"
    }
)

In [7]:
display(cpi_hist.head())
display(cpi_hist.tail())

        date  cpi_combined
0 2013-01-01         104.6
1 2013-02-01         105.3
2 2013-03-01         105.5
3 2013-04-01         106.1
4 2013-05-01         106.9

          date  cpi_combined
151 2025-08-01         197.0
152 2025-09-01         197.0
153 2025-10-01         197.3
154 2025-11-01         197.9
155 2025-12-01         198.0

In [8]:
cpi_rural = pd.read_csv(
    RAW_CPI / r"C:\Users\Adity\OneDrive\Desktop\RESEARCH\Project Work\Inflation-Forecasting-Dashboard\cpi_rural_current_2024base.csv"
)

cpi_rural["date"] = pd.to_datetime(
    cpi_rural["year"].astype(str)
    + "-"
    + cpi_rural["month_code"].astype(str)
    + "-01"
)

cpi_rural = (
    cpi_rural[
        ["date", "index"]
    ]
    .rename(columns={"index": "cpi_rural"})
    .sort_values("date")
)

In [9]:
cpi_urban = pd.read_csv(
    RAW_CPI / r"C:\Users\Adity\OneDrive\Desktop\RESEARCH\Project Work\Inflation-Forecasting-Dashboard\cpi_urban_current_2024base.csv"
)

cpi_urban["date"] = pd.to_datetime(
    cpi_urban["year"].astype(str)
    + "-"
    + cpi_urban["month_code"].astype(str)
    + "-01"
)

cpi_urban = (
    cpi_urban[
        ["date", "index"]
    ]
    .rename(columns={"index": "cpi_urban"})
    .sort_values("date")
)

In [10]:
cpi_food = pd.read_csv(
    RAW_CPI / r"C:\Users\Adity\OneDrive\Desktop\RESEARCH\Project Work\Inflation-Forecasting-Dashboard\cpi_rural_current_2024base.csv"
)

In [11]:
wpi = pd.read_excel(
    RAW_WPI / r"C:\Users\Adity\OneDrive\Desktop\RESEARCH\Project Work\Inflation-Forecasting-Dashboard\wpi_monthly_2022_23base.xlsx",
    sheet_name="Sheet3",
    engine="openpyxl"
)

print(wpi.shape)
display(wpi.head())

(1137, 44)

,Level,Commodity Name,Commodity Code,Commodity Weight,Apr-23,May-23,Jun-23,Jul-23,Aug-23,Sep-23,Oct-23,Nov-23,Dec-23,Jan-24,Feb-24,Mar-24,Apr-24,May-24,Jun-24,Jul-24,Aug-24,Sep-24,Oct-24,Nov-24,Dec-24,Jan-25,Feb-25,Mar-25,Apr-25,May-25,Jun-25,Jul-25,Aug-25,Sep-25,Oct-25,Nov-25,Dec-25,Jan-26,Feb-26,Mar-26,Apr-26,May-26,Jun-26,Jul-26
0,ALL,All Commodities,1.000000e+09,100.00000,99.0,98.6,98.3,99.1,99.5,99.6,100.1,100.1,99.4,99.3,99.3,99.4,99.9,100.4,100.7,101.0,100.8,101.2,102.1,102.1,101.6,101.1,100.9,100.6,100.5,100.2,100.3,100.2,100.8,101.0,100.9,101.5,101.9,102.3,103.1,104.6,108.9,110.1,110.2,110.0
1,Major Group,I PRIMARY ARTICLES,1.100000e+09,22.75730,102.0,102.3,103.3,107.9,108.0,106.4,107.8,108.9,107.2,107.4,107.9,108.1,108.8,110.1,111.8,113.1,113.8,115.4,117.1,117.1,115.2,112.2,109.8,108.6,108.5,108.3,108.5,108.0,109.6,110.7,110.4,112.3,112.0,112.1,111.6,111.4,112.8,114.0,116.1,117.2
2,Group,(A). FOOD ARTICLES,1.101000e+09,15.97835,102.4,103.6,105.8,111.3,111.3,108.6,110.5,112.5,110.3,109.7,110.4,110.5,112.1,114.0,116.5,118.2,119.1,121.2,123.0,122.5,119.8,115.4,112.2,111.1,111.3,111.0,111.2,112.1,112.9,113.0,112.6,115.2,114.5,113.9,113.1,112.8,114.2,115.1,117.3,118.2
3,Sub Group,a. Food Grains (Cereals+Pulses),1.101010e+09,3.60359,103.0,103.2,104.6,105.9,107.7,110.1,112.0,114.0,114.4,114.6,115.5,114.5,114.3,114.9,116.6,117.7,119.0,119.9,119.9,121.5,121.6,122.0,121.6,119.3,116.5,114.6,113.9,114.8,115.8,115.3,114.7,115.3,116.1,116.5,115.6,114.3,114.6,115.1,115.7,117.5
4,S_S_Group,a1. Cereals,1.101010e+09,3.03974,102.7,102.9,104.1,105.4,106.9,108.3,110.3,112.3,113.1,114.1,114.7,113.6,112.9,112.9,114.3,115.7,117.0,117.9,118.2,120.4,121.2,122.2,122.5,120.1,116.9,115.0,114.5,115.6,116.4,116.1,115.5,116.2,117.4,117.6,116.4,115.0,115.2,115.5,116.0,117.9

In [12]:
wpi_targets = [
    "All Commodities",
    "I PRIMARY ARTICLES",
    "II FUEL & POWER",
    "III MANUFACTURED PRODUCTS"
]

In [13]:
for target in wpi_targets:
    print("\n", target)
    display(
        wpi[
            wpi["Commodity Name"]
            .astype(str)
            .str.contains(
                target,
                case=False,
                na=False
            )
        ][
            [
                "Level",
                "Commodity Name",
                "Commodity Code",
                "Commodity Weight"
            ]
        ]
    )

 All Commodities

  Level   Commodity Name  Commodity Code  Commodity Weight
0   ALL  All Commodities    1.000000e+09             100.0

 I PRIMARY ARTICLES

         Level      Commodity Name  Commodity Code  Commodity Weight
1  Major Group  I PRIMARY ARTICLES    1.100000e+09           22.7573

 II FUEL & POWER

           Level   Commodity Name  Commodity Code  Commodity Weight
152  Major Group  II FUEL & POWER    1.200000e+09          14.11433

 III MANUFACTURED PRODUCTS

Empty DataFrame
Columns: [Level, Commodity Name, Commodity Code, Commodity Weight]
Index: []

In [14]:
ppi = pd.read_excel(
    RAW_PPI / r"C:\Users\Adity\OneDrive\Desktop\RESEARCH\Project Work\Inflation-Forecasting-Dashboard\output_ppi_monthly_2022_23base.xlsx",
    sheet_name="Sheet2",
    engine="openpyxl"
)

print(ppi.shape)
display(ppi.head())

(161, 44)

,Level,Commodity Code,Commodity Name,Commodity Weight,Apr-23,May-23,Jun-23,Jul-23,Aug-23,Sep-23,Oct-23,Nov-23,Dec-23,Jan-24,Feb-24,Mar-24,Apr-24,May-24,Jun-24,Jul-24,Aug-24,Sep-24,Oct-24,Nov-24,Dec-24,Jan-25,Feb-25,Mar-25,Apr-25,May-25,Jun-25,Jul-25,Aug-25,Sep-25,Oct-25,Nov-25,Dec-25,Jan-26,Feb-26,Mar-26,Apr-26,May-26,Jun-26,Jul-26
0,All,1000000000,ALL COMMODITIES,100.00000,99.1,98.6,98.2,99.1,99.4,99.6,100.0,99.9,99.2,99.2,99.2,99.2,99.7,100.1,100.4,100.8,100.7,101.0,101.8,102.0,101.5,101.2,101.0,100.7,100.5,100.2,100.3,100.3,100.9,101.0,101.1,101.7,102.1,102.6,103.3,104.9,108.8,109.9,109.9,109.9
1,Major Group,1100000000,"AGRICULTURE, FORESTRY AND FISHING",22.15648,102.4,102.5,103.4,107.4,107.8,106.9,108.0,108.9,107.0,106.9,106.9,107.1,107.6,108.4,109.8,111.3,112.1,113.8,115.1,115.2,113.9,111.3,109.2,107.8,107.5,107.0,107.1,107.2,108.6,109.4,109.6,111.5,111.3,111.3,110.8,110.6,111.4,112.1,114.1,115.6
2,Group,1101000000,"CROP AND ANIMAL PRODUCTION, HUNTING AND RELATE...",19.03219,102.5,102.2,103.3,108.0,108.3,107.7,108.9,110.2,107.9,107.1,107.1,107.4,107.7,108.3,110.1,112.2,112.6,114.6,116.2,116.3,114.8,111.6,109.2,107.9,107.6,106.5,106.6,108.3,109.5,109.6,109.8,112.1,111.9,111.7,111.3,111.0,111.5,111.9,114.3,116.1
3,SUT Product Category,1101010000,Paddy,1.57272,104.7,106.0,107.6,109.9,110.7,112.5,114.6,115.9,116.9,118.5,119.5,119.0,118.7,118.4,119.6,120.6,121.1,121.0,120.0,121.6,122.0,121.1,121.0,120.5,119.5,117.4,116.8,118.0,117.9,118.0,118.1,119.7,121.4,121.0,120.9,120.4,119.3,119.6,120.4,121.7
4,SUT Product Category,1101020000,Wheat,0.96605,99.2,98.7,100.5,100.4,103.1,104.6,107.1,109.7,110.0,109.9,109.9,108.0,106.0,106.0,107.9,109.4,111.7,114.0,117.7,121.3,122.8,126.4,127.5,121.1,114.1,112.3,111.5,113.1,115.4,115.0,114.4,114.2,114.5,116.2,113.5,110.8,113.4,113.4,112.4,114.4

In [15]:
ppi_all = ppi[
    ppi["Commodity Name"]
    .astype(str)
    .str.fullmatch(
        "ALL COMMODITIES",
        case=False,
        na=False
    )
]

display(
    ppi_all[
        [
            "Level",
            "Commodity Code",
            "Commodity Name",
            "Commodity Weight"
        ]
    ]
)

  Level  Commodity Code   Commodity Name  Commodity Weight
0   All      1000000000  ALL COMMODITIES             100.0

In [16]:
print("Available WPI aggregate candidates:\n")

wpi_candidates = wpi[
    wpi["Commodity Name"]
    .astype(str)
    .str.contains(
        "All Commodities|Primary|Fuel|Manufactured",
        case=False,
        na=False,
        regex=True
    )
][
    [
        "Level",
        "Commodity Name",
        "Commodity Code",
        "Commodity Weight"
    ]
]

display(wpi_candidates)

Available WPI aggregate candidates:

,Level,Commodity Name,Commodity Code,Commodity Weight
0,ALL,All Commodities,1.000000e+09,100.00000
1,Major Group,I PRIMARY ARTICLES,1.100000e+09,22.75730
152,Major Group,II FUEL & POWER,1.200000e+09,14.11433
190,Major Group,III. MANUFACTURED PRODUCTS,1.300000e+09,63.12837
477,Sub Group,c.Manufacture of plastics and synthetic rubber...,1.310030e+09,0.82578
607,Item,Fuel hose & pipes auto,1.312020e+09,0.00751
919,Item,"Engine Components – Pistons, Valves (Inlet & E...",1.318010e+09,0.05348
1036,Item,"Fuel injection equipment,excl injection pump f...",1.319030e+09,0.01227

In [17]:
wpi_month_columns = wpi.columns[4:]

print("Number of monthly columns:", len(wpi_month_columns))
print("First 5:", wpi_month_columns[:5].tolist())
print("Last 5:", wpi_month_columns[-5:].tolist())

Number of monthly columns: 40
First 5: ['Apr-23', 'May-23', 'Jun-23', 'Jul-23', 'Aug-23']
Last 5: ['Mar-26', 'Apr-26', 'May-26', 'Jun-26', 'Jul-26']

In [18]:
wpi_core = wpi[
    wpi["Commodity Name"].astype(str).isin([
        "All Commodities",
        "I PRIMARY ARTICLES",
        "II FUEL & POWER",
        "III MANUFACTURED PRODUCTS"
    ])
].copy()

display(
    wpi_core[
        ["Level", "Commodity Name", "Commodity Code", "Commodity Weight"]
    ]
)

           Level      Commodity Name  Commodity Code  Commodity Weight
0            ALL     All Commodities    1.000000e+09         100.00000
1    Major Group  I PRIMARY ARTICLES    1.100000e+09          22.75730
152  Major Group     II FUEL & POWER    1.200000e+09          14.11433

In [20]:
manufacturing_candidates = wpi[
    wpi["Commodity Name"]
    .astype(str)
    .str.contains(
        "MANUFACT",
        case=False,
        na=False
    )
][
    [
        "Level",
        "Commodity Name",
        "Commodity Code",
        "Commodity Weight"
    ]
]

display(manufacturing_candidates)

,Level,Commodity Name,Commodity Code,Commodity Weight
190,Major Group,III. MANUFACTURED PRODUCTS,1.300000e+09,63.12837
191,Group,(A).MANUFACTURE OF FOOD PRODUCTS,1.301000e+09,9.02016
213,Sub Group,d.Manufacture of vegetable and animal oils and...,1.301040e+09,1.96540
226,Sub Group,e.Manufacture of dairy products,1.301050e+09,1.29749
234,Sub Group,f.Manufacture of grain mill products,1.301060e+09,1.85895
...,...,...,...,...
1099,Sub Group,c.Manufacture of musical instruments,1.322030e+09,0.00344
1101,Sub Group,d.Manufacture of sports goods,1.322040e+09,0.02920
1109,Sub Group,e.Manufacture of games and toys,1.322050e+09,0.02316
1114,Sub Group,f.Manufacture of medical and dental instrument...,1.322060e+09,0.16553
1123,Sub Group,g.Other manufacturing,1.322070e+09,0.16923

In [21]:
wpi[
    wpi["Commodity Name"].astype(str).str.contains(
        "All Commodities|PRIMARY ARTICLES|FUEL|MANUFACT",
        case=False,
        na=False,
        regex=True
    )
][
    [
        "Level",
        "Commodity Name",
        "Commodity Code",
        "Commodity Weight"
    ]
]

,Level,Commodity Name,Commodity Code,Commodity Weight
0,ALL,All Commodities,1.000000e+09,100.00000
1,Major Group,I PRIMARY ARTICLES,1.100000e+09,22.75730
152,Major Group,II FUEL & POWER,1.200000e+09,14.11433
190,Major Group,III. MANUFACTURED PRODUCTS,1.300000e+09,63.12837
191,Group,(A).MANUFACTURE OF FOOD PRODUCTS,1.301000e+09,9.02016
...,...,...,...,...
1099,Sub Group,c.Manufacture of musical instruments,1.322030e+09,0.00344
1101,Sub Group,d.Manufacture of sports goods,1.322040e+09,0.02920
1109,Sub Group,e.Manufacture of games and toys,1.322050e+09,0.02316
1114,Sub Group,f.Manufacture of medical and dental instrument...,1.322060e+09,0.16553
1123,Sub Group,g.Other manufacturing,1.322070e+09,0.16923

In [22]:
wpi_core = wpi[
    wpi["Commodity Name"].isin([
        "All Commodities",
        "I PRIMARY ARTICLES",
        "II FUEL & POWER",
        "III. MANUFACTURED PRODUCTS"
    ])
].copy()

display(
    wpi_core[
        [
            "Level",
            "Commodity Name",
            "Commodity Code",
            "Commodity Weight"
        ]
    ]
)

           Level              Commodity Name  Commodity Code  Commodity Weight
0            ALL             All Commodities    1.000000e+09         100.00000
1    Major Group          I PRIMARY ARTICLES    1.100000e+09          22.75730
152  Major Group             II FUEL & POWER    1.200000e+09          14.11433
190  Major Group  III. MANUFACTURED PRODUCTS    1.300000e+09          63.12837

In [23]:
wpi_month_columns = wpi.columns[4:]

print("Number of monthly columns:", len(wpi_month_columns))
print("First 5:", wpi_month_columns[:5].tolist())
print("Last 5:", wpi_month_columns[-5:].tolist())

Number of monthly columns: 40
First 5: ['Apr-23', 'May-23', 'Jun-23', 'Jul-23', 'Aug-23']
Last 5: ['Mar-26', 'Apr-26', 'May-26', 'Jun-26', 'Jul-26']

In [24]:
wpi_long = wpi_core.melt(
    id_vars=[
        "Level",
        "Commodity Name",
        "Commodity Code",
        "Commodity Weight"
    ],
    value_vars=wpi_month_columns,
    var_name="month",
    value_name="index"
)

display(wpi_long.head(10))

,Level,Commodity Name,Commodity Code,Commodity Weight,month,index
0,ALL,All Commodities,1.000000e+09,100.00000,Apr-23,99.0
1,Major Group,I PRIMARY ARTICLES,1.100000e+09,22.75730,Apr-23,102.0
2,Major Group,II FUEL & POWER,1.200000e+09,14.11433,Apr-23,94.0
3,Major Group,III. MANUFACTURED PRODUCTS,1.300000e+09,63.12837,Apr-23,99.1
4,ALL,All Commodities,1.000000e+09,100.00000,May-23,98.6
5,Major Group,I PRIMARY ARTICLES,1.100000e+09,22.75730,May-23,102.3
6,Major Group,II FUEL & POWER,1.200000e+09,14.11433,May-23,91.4
7,Major Group,III. MANUFACTURED PRODUCTS,1.300000e+09,63.12837,May-23,98.9
8,ALL,All Commodities,1.000000e+09,100.00000,Jun-23,98.3
9,Major Group,I PRIMARY ARTICLES,1.100000e+09,22.75730,Jun-23,103.3

In [25]:
wpi_long["date"] = pd.to_datetime(
    wpi_long["month"],
    format="%b-%y"
)
wpi_long = wpi_long.sort_values(
    ["date", "Commodity Name"]
).reset_index(drop=True)

In [26]:
display(
    wpi_long[
        ["date", "Commodity Name", "index"]
    ].head(20)
)

         date              Commodity Name  index
0  2023-04-01             All Commodities   99.0
1  2023-04-01          I PRIMARY ARTICLES  102.0
2  2023-04-01             II FUEL & POWER   94.0
3  2023-04-01  III. MANUFACTURED PRODUCTS   99.1
4  2023-05-01             All Commodities   98.6
5  2023-05-01          I PRIMARY ARTICLES  102.3
6  2023-05-01             II FUEL & POWER   91.4
7  2023-05-01  III. MANUFACTURED PRODUCTS   98.9
8  2023-06-01             All Commodities   98.3
9  2023-06-01          I PRIMARY ARTICLES  103.3
10 2023-06-01             II FUEL & POWER   90.5
11 2023-06-01  III. MANUFACTURED PRODUCTS   98.2
12 2023-07-01             All Commodities   99.1
13 2023-07-01          I PRIMARY ARTICLES  107.9
14 2023-07-01             II FUEL & POWER   90.6
15 2023-07-01  III. MANUFACTURED PRODUCTS   97.8
16 2023-08-01             All Commodities   99.5
17 2023-08-01          I PRIMARY ARTICLES  108.0
18 2023-08-01             II FUEL & POWER   91.8
19 2023-08-01  III. MANUFACTURED PRODUCTS   98.1

In [27]:
wpi_long["series"] = wpi_long["Commodity Name"].map({
    "All Commodities": "wpi_all",
    "I PRIMARY ARTICLES": "wpi_primary",
    "II FUEL & POWER": "wpi_fuel",
    "III. MANUFACTURED PRODUCTS": "wpi_manufacturing"
})
print(wpi_long["series"].unique())

['wpi_all' 'wpi_primary' 'wpi_fuel' 'wpi_manufacturing']

In [28]:
wpi_master = wpi_long.pivot(
    index="date",
    columns="series",
    values="index"
).reset_index()
wpi_master.columns.name = None

In [29]:
display(wpi_master.head())
display(wpi_master.tail())

        date  wpi_all  wpi_fuel  wpi_manufacturing  wpi_primary
0 2023-04-01     99.0      94.0               99.1        102.0
1 2023-05-01     98.6      91.4               98.9        102.3
2 2023-06-01     98.3      90.5               98.2        103.3
3 2023-07-01     99.1      90.6               97.8        107.9
4 2023-08-01     99.5      91.8               98.1        108.0

         date  wpi_all  wpi_fuel  wpi_manufacturing  wpi_primary
35 2026-03-01    104.6      93.5              104.7        111.4
36 2026-04-01    108.9     111.0              107.0        112.8
37 2026-05-01    110.1     113.4              108.0        114.0
38 2026-06-01    110.2     111.1              107.8        116.1
39 2026-07-01    110.0     105.4              108.4        117.2

In [30]:
wpi_master = wpi_long.pivot(
    index="date",
    columns="series",
    values="index"
).reset_index()
wpi_master.columns.name = None

In [31]:
display(wpi_master.head())
display(wpi_master.tail())

        date  wpi_all  wpi_fuel  wpi_manufacturing  wpi_primary
0 2023-04-01     99.0      94.0               99.1        102.0
1 2023-05-01     98.6      91.4               98.9        102.3
2 2023-06-01     98.3      90.5               98.2        103.3
3 2023-07-01     99.1      90.6               97.8        107.9
4 2023-08-01     99.5      91.8               98.1        108.0

         date  wpi_all  wpi_fuel  wpi_manufacturing  wpi_primary
35 2026-03-01    104.6      93.5              104.7        111.4
36 2026-04-01    108.9     111.0              107.0        112.8
37 2026-05-01    110.1     113.4              108.0        114.0
38 2026-06-01    110.2     111.1              107.8        116.1
39 2026-07-01    110.0     105.4              108.4        117.2

In [32]:
print("Rows:", len(wpi_master))
print("Missing values:")
print(wpi_master.isna().sum())
print(
    "Duplicate dates:",
    wpi_master["date"].duplicated().sum()
)

Rows: 40
Missing values:
date                 0
wpi_all              0
wpi_fuel             0
wpi_manufacturing    0
wpi_primary          0
dtype: int64
Duplicate dates: 0

In [33]:
expected_wpi_dates = pd.date_range(
    wpi_master["date"].min(),
    wpi_master["date"].max(),
    freq="MS"
)

missing_wpi_dates = expected_wpi_dates.difference(
    wpi_master["date"]
)

print("Expected months:", len(expected_wpi_dates))
print("Actual months:", len(wpi_master))
print("Missing months:", len(missing_wpi_dates))
print(missing_wpi_dates)

Expected months: 40
Actual months: 40
Missing months: 0
DatetimeIndex([], dtype='datetime64[ns]', freq='MS')

In [34]:
for column in [
    "wpi_all",
    "wpi_primary",
    "wpi_fuel",
    "wpi_manufacturing"
]:
    wpi_master[f"{column}_yoy"] = (
        wpi_master[column]
        .pct_change(12)
        * 100
    )

In [35]:
display(wpi_master.head(15))

,date,wpi_all,wpi_fuel,wpi_manufacturing,wpi_primary,wpi_all_yoy,wpi_primary_yoy,wpi_fuel_yoy,wpi_manufacturing_yoy
0,2023-04-01,99.0,94.0,99.1,102.0,NaN,NaN,NaN,NaN
1,2023-05-01,98.6,91.4,98.9,102.3,NaN,NaN,NaN,NaN
2,2023-06-01,98.3,90.5,98.2,103.3,NaN,NaN,NaN,NaN
3,2023-07-01,99.1,90.6,97.8,107.9,NaN,NaN,NaN,NaN
4,2023-08-01,99.5,91.8,98.1,108.0,NaN,NaN,NaN,NaN
5,2023-09-01,99.6,94.2,98.3,106.4,NaN,NaN,NaN,NaN
6,2023-10-01,100.1,95.2,98.4,107.8,NaN,NaN,NaN,NaN
7,2023-11-01,100.1,94.2,98.2,108.9,NaN,NaN,NaN,NaN
8,2023-12-01,99.4,93.5,97.9,107.2,NaN,NaN,NaN,NaN
9,2024-01-01,99.3,93.7,97.7,107.4,NaN,NaN,NaN,NaN
10,2024-02-01,99.3,93.6,97.4,107.9,NaN,NaN,NaN,NaN
11,2024-03-01,99.4,93.3,97.7,108.1,NaN,NaN,NaN,NaN
12,2024-04-01,99.9,92.0,98.5,108.8,0.909091,6.666667,-2.127660,-0.605449
13,2024-05-01,100.4,91.7,98.9,110.1,1.825558,7.624633,0.328228,0.000000
14,2024-06-01,100.7,89.9,99.1,111.8,2.441506,8.228461,-0.662983,0.916497

In [36]:
wpi_master.to_csv(
    PROCESSED / "wpi_master_monthly.csv",
    index=False
)

In [37]:
print(
    "Saved to:",
    PROCESSED / "wpi_master_monthly.csv"
)

Saved to: C:\Users\Adity\OneDrive\Desktop\RESEARCH\Project Work\Inflation-Forecasting-Dashboard\data\processed\wpi_master_monthly.csv

In [38]:
display(wpi_master.head())
display(wpi_master.tail())

print("Missing:", wpi_master.isna().sum())
print("Duplicates:", wpi_master["date"].duplicated().sum())

,date,wpi_all,wpi_fuel,wpi_manufacturing,wpi_primary,wpi_all_yoy,wpi_primary_yoy,wpi_fuel_yoy,wpi_manufacturing_yoy
0,2023-04-01,99.0,94.0,99.1,102.0,NaN,NaN,NaN,NaN
1,2023-05-01,98.6,91.4,98.9,102.3,NaN,NaN,NaN,NaN
2,2023-06-01,98.3,90.5,98.2,103.3,NaN,NaN,NaN,NaN
3,2023-07-01,99.1,90.6,97.8,107.9,NaN,NaN,NaN,NaN
4,2023-08-01,99.5,91.8,98.1,108.0,NaN,NaN,NaN,NaN

,date,wpi_all,wpi_fuel,wpi_manufacturing,wpi_primary,wpi_all_yoy,wpi_primary_yoy,wpi_fuel_yoy,wpi_manufacturing_yoy
35,2026-03-01,104.6,93.5,104.7,111.4,3.976143,2.578269,3.200883,4.804805
36,2026-04-01,108.9,111.0,107.0,112.8,8.358209,3.963134,25.000000,6.679960
37,2026-05-01,110.1,113.4,108.0,114.0,9.880240,5.263158,30.795848,7.676969
38,2026-06-01,110.2,111.1,107.8,116.1,9.870389,7.004608,27.408257,7.477567
39,2026-07-01,110.0,105.4,108.4,117.2,9.780439,8.518519,20.045558,8.291708

Missing: date                      0
wpi_all                   0
wpi_fuel                  0
wpi_manufacturing         0
wpi_primary               0
wpi_all_yoy              12
wpi_primary_yoy          12
wpi_fuel_yoy             12
wpi_manufacturing_yoy    12
dtype: int64
Duplicates: 0

In [39]:
ppi = pd.read_excel(
    r"C:\Users\Adity\OneDrive\Desktop\RESEARCH\Project Work\Inflation-Forecasting-Dashboard\output_ppi_monthly_2022_23base.xlsx",
    sheet_name="Sheet2",
    engine="openpyxl"
)

print("Shape:", ppi.shape)
display(ppi.head())

Shape: (161, 44)

,Level,Commodity Code,Commodity Name,Commodity Weight,Apr-23,May-23,Jun-23,Jul-23,Aug-23,Sep-23,Oct-23,Nov-23,Dec-23,Jan-24,Feb-24,Mar-24,Apr-24,May-24,Jun-24,Jul-24,Aug-24,Sep-24,Oct-24,Nov-24,Dec-24,Jan-25,Feb-25,Mar-25,Apr-25,May-25,Jun-25,Jul-25,Aug-25,Sep-25,Oct-25,Nov-25,Dec-25,Jan-26,Feb-26,Mar-26,Apr-26,May-26,Jun-26,Jul-26
0,All,1000000000,ALL COMMODITIES,100.00000,99.1,98.6,98.2,99.1,99.4,99.6,100.0,99.9,99.2,99.2,99.2,99.2,99.7,100.1,100.4,100.8,100.7,101.0,101.8,102.0,101.5,101.2,101.0,100.7,100.5,100.2,100.3,100.3,100.9,101.0,101.1,101.7,102.1,102.6,103.3,104.9,108.8,109.9,109.9,109.9
1,Major Group,1100000000,"AGRICULTURE, FORESTRY AND FISHING",22.15648,102.4,102.5,103.4,107.4,107.8,106.9,108.0,108.9,107.0,106.9,106.9,107.1,107.6,108.4,109.8,111.3,112.1,113.8,115.1,115.2,113.9,111.3,109.2,107.8,107.5,107.0,107.1,107.2,108.6,109.4,109.6,111.5,111.3,111.3,110.8,110.6,111.4,112.1,114.1,115.6
2,Group,1101000000,"CROP AND ANIMAL PRODUCTION, HUNTING AND RELATE...",19.03219,102.5,102.2,103.3,108.0,108.3,107.7,108.9,110.2,107.9,107.1,107.1,107.4,107.7,108.3,110.1,112.2,112.6,114.6,116.2,116.3,114.8,111.6,109.2,107.9,107.6,106.5,106.6,108.3,109.5,109.6,109.8,112.1,111.9,111.7,111.3,111.0,111.5,111.9,114.3,116.1
3,SUT Product Category,1101010000,Paddy,1.57272,104.7,106.0,107.6,109.9,110.7,112.5,114.6,115.9,116.9,118.5,119.5,119.0,118.7,118.4,119.6,120.6,121.1,121.0,120.0,121.6,122.0,121.1,121.0,120.5,119.5,117.4,116.8,118.0,117.9,118.0,118.1,119.7,121.4,121.0,120.9,120.4,119.3,119.6,120.4,121.7
4,SUT Product Category,1101020000,Wheat,0.96605,99.2,98.7,100.5,100.4,103.1,104.6,107.1,109.7,110.0,109.9,109.9,108.0,106.0,106.0,107.9,109.4,111.7,114.0,117.7,121.3,122.8,126.4,127.5,121.1,114.1,112.3,111.5,113.1,115.4,115.0,114.4,114.2,114.5,116.2,113.5,110.8,113.4,113.4,112.4,114.4

In [40]:
ppi_targets = ppi[
    ppi["Commodity Name"]
    .astype(str)
    .str.contains(
        "ALL COMMODITIES",
        case=False,
        na=False
    )
][
    ["Level", "Commodity Code", "Commodity Name", "Commodity Weight"]
]

display(ppi_targets)

  Level  Commodity Code   Commodity Name  Commodity Weight
0   All      1000000000  ALL COMMODITIES             100.0

In [41]:
ppi_month_columns = ppi.columns[4:]

print("Number of monthly columns:", len(ppi_month_columns))
print("First 5:", ppi_month_columns[:5].tolist())
print("Last 5:", ppi_month_columns[-5:].tolist())

Number of monthly columns: 40
First 5: ['Apr-23', 'May-23', 'Jun-23', 'Jul-23', 'Aug-23']
Last 5: ['Mar-26', 'Apr-26', 'May-26', 'Jun-26', 'Jul-26']

In [42]:
ppi_all = ppi[
    ppi["Commodity Name"]
    .astype(str)
    .str.fullmatch(
        "ALL COMMODITIES",
        case=False,
        na=False
    )
].copy()

print("Headline PPI rows:", len(ppi_all))

display(
    ppi_all[
        ["Level", "Commodity Code",
         "Commodity Name", "Commodity Weight"]
    ]
)

Headline PPI rows: 1

  Level  Commodity Code   Commodity Name  Commodity Weight
0   All      1000000000  ALL COMMODITIES             100.0

In [44]:
ppi_master = pd.DataFrame({
    "date": pd.to_datetime(
        ppi_month_columns,
        format="%b-%y"
    ),
    "output_ppi": pd.to_numeric(
        ppi_all.iloc[0][ppi_month_columns].values,
        errors="coerce"
    )
})
ppi_master = (
    ppi_master
    .sort_values("date")
    .reset_index(drop=True)
)

In [45]:
display(ppi_master.head())
display(ppi_master.tail())

        date  output_ppi
0 2023-04-01        99.1
1 2023-05-01        98.6
2 2023-06-01        98.2
3 2023-07-01        99.1
4 2023-08-01        99.4

         date  output_ppi
35 2026-03-01       104.9
36 2026-04-01       108.8
37 2026-05-01       109.9
38 2026-06-01       109.9
39 2026-07-01       109.9

In [46]:
print("Start:", ppi_master["date"].min())
print("End:", ppi_master["date"].max())
print("Observations:", len(ppi_master))

Start: 2023-04-01 00:00:00
End: 2026-07-01 00:00:00
Observations: 40

In [48]:
print(
    "Missing PPI:",
    ppi_master["output_ppi"].isna().sum()
)
print(
    "Duplicate dates:",
    ppi_master["date"].duplicated().sum()
)

Missing PPI: 0
Duplicate dates: 0

In [49]:
expected_ppi_dates = pd.date_range(
    start=ppi_master["date"].min(),
    end=ppi_master["date"].max(),
    freq="MS"
)

missing_ppi_dates = expected_ppi_dates.difference(
    ppi_master["date"]
)

print("Expected months:", len(expected_ppi_dates))
print("Actual months:", len(ppi_master))
print("Missing months:", len(missing_ppi_dates))
print(missing_ppi_dates)

Expected months: 40
Actual months: 40
Missing months: 0
DatetimeIndex([], dtype='datetime64[ns]', freq='MS')

In [50]:
ppi_master["output_ppi_yoy"] = (
    ppi_master["output_ppi"]
    .pct_change(12)
    * 100
)
display(
    ppi_master[
        ["date", "output_ppi", "output_ppi_yoy"]
    ].tail(20)
)

         date  output_ppi  output_ppi_yoy
20 2024-12-01       101.5        2.318548
21 2025-01-01       101.2        2.016129
22 2025-02-01       101.0        1.814516
23 2025-03-01       100.7        1.512097
24 2025-04-01       100.5        0.802407
25 2025-05-01       100.2        0.099900
26 2025-06-01       100.3       -0.099602
27 2025-07-01       100.3       -0.496032
28 2025-08-01       100.9        0.198610
29 2025-09-01       101.0        0.000000
30 2025-10-01       101.1       -0.687623
31 2025-11-01       101.7       -0.294118
32 2025-12-01       102.1        0.591133
33 2026-01-01       102.6        1.383399
34 2026-02-01       103.3        2.277228
35 2026-03-01       104.9        4.170804
36 2026-04-01       108.8        8.258706
37 2026-05-01       109.9        9.680639
38 2026-06-01       109.9        9.571286
39 2026-07-01       109.9        9.571286

In [51]:
ppi_master.to_csv(
    PROCESSED / "ppi_master_monthly.csv",
    index=False
)

print(
    "Saved:",
    PROCESSED / "ppi_master_monthly.csv"
)

Saved: C:\Users\Adity\OneDrive\Desktop\RESEARCH\Project Work\Inflation-Forecasting-Dashboard\data\processed\ppi_master_monthly.csv

In [52]:
print("========== PPI FINAL CHECK ==========")

print("Start:", ppi_master["date"].min())
print("End:", ppi_master["date"].max())
print("Observations:", len(ppi_master))
print("Missing:", ppi_master["output_ppi"].isna().sum())
print("Duplicate dates:", ppi_master["date"].duplicated().sum())
print(
    "Non-positive values:",
    (ppi_master["output_ppi"] <= 0).sum()
)

print("=====================================")

========== PPI FINAL CHECK ==========
Start: 2023-04-01 00:00:00
End: 2026-07-01 00:00:00
Observations: 40
Missing: 0
Duplicate dates: 0
Non-positive values: 0
=====================================

In [53]:
print("CPI Historical:")
display(cpi_hist.head())

print("\nWPI Master:")
display(wpi_master.head())

print("\nPPI Master:")
display(ppi_master.head())

CPI Historical:

        date  cpi_combined
0 2013-01-01         104.6
1 2013-02-01         105.3
2 2013-03-01         105.5
3 2013-04-01         106.1
4 2013-05-01         106.9

WPI Master:

,date,wpi_all,wpi_fuel,wpi_manufacturing,wpi_primary,wpi_all_yoy,wpi_primary_yoy,wpi_fuel_yoy,wpi_manufacturing_yoy
0,2023-04-01,99.0,94.0,99.1,102.0,NaN,NaN,NaN,NaN
1,2023-05-01,98.6,91.4,98.9,102.3,NaN,NaN,NaN,NaN
2,2023-06-01,98.3,90.5,98.2,103.3,NaN,NaN,NaN,NaN
3,2023-07-01,99.1,90.6,97.8,107.9,NaN,NaN,NaN,NaN
4,2023-08-01,99.5,91.8,98.1,108.0,NaN,NaN,NaN,NaN

PPI Master:

        date  output_ppi  output_ppi_yoy
0 2023-04-01        99.1             NaN
1 2023-05-01        98.6             NaN
2 2023-06-01        98.2             NaN
3 2023-07-01        99.1             NaN
4 2023-08-01        99.4             NaN

In [54]:
cpi_core = cpi_hist.copy()

display(cpi_core.head())
display(cpi_core.tail())

        date  cpi_combined
0 2013-01-01         104.6
1 2013-02-01         105.3
2 2013-03-01         105.5
3 2013-04-01         106.1
4 2013-05-01         106.9

          date  cpi_combined
151 2025-08-01         197.0
152 2025-09-01         197.0
153 2025-10-01         197.3
154 2025-11-01         197.9
155 2025-12-01         198.0

In [55]:
master_long = pd.merge(
    cpi_core,
    wpi_master,
    on="date",
    how="outer"
)

master_long = (
    master_long
    .sort_values("date")
    .reset_index(drop=True)
)

display(master_long.head())
display(master_long.tail())

,date,cpi_combined,wpi_all,wpi_fuel,wpi_manufacturing,wpi_primary,wpi_all_yoy,wpi_primary_yoy,wpi_fuel_yoy,wpi_manufacturing_yoy
0,2013-01-01,104.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2013-02-01,105.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2013-03-01,105.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2013-04-01,106.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2013-05-01,106.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,date,cpi_combined,wpi_all,wpi_fuel,wpi_manufacturing,wpi_primary,wpi_all_yoy,wpi_primary_yoy,wpi_fuel_yoy,wpi_manufacturing_yoy
158,2026-03-01,NaN,104.6,93.5,104.7,111.4,3.976143,2.578269,3.200883,4.804805
159,2026-04-01,NaN,108.9,111.0,107.0,112.8,8.358209,3.963134,25.000000,6.679960
160,2026-05-01,NaN,110.1,113.4,108.0,114.0,9.880240,5.263158,30.795848,7.676969
161,2026-06-01,NaN,110.2,111.1,107.8,116.1,9.870389,7.004608,27.408257,7.477567
162,2026-07-01,NaN,110.0,105.4,108.4,117.2,9.780439,8.518519,20.045558,8.291708

In [56]:
master_long = pd.merge(
    cpi_core,
    wpi_master,
    on="date",
    how="outer"
)

master_long = (
    master_long
    .sort_values("date")
    .reset_index(drop=True)
)

display(master_long.head())
display(master_long.tail())

,date,cpi_combined,wpi_all,wpi_fuel,wpi_manufacturing,wpi_primary,wpi_all_yoy,wpi_primary_yoy,wpi_fuel_yoy,wpi_manufacturing_yoy
0,2013-01-01,104.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2013-02-01,105.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2013-03-01,105.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2013-04-01,106.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2013-05-01,106.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,date,cpi_combined,wpi_all,wpi_fuel,wpi_manufacturing,wpi_primary,wpi_all_yoy,wpi_primary_yoy,wpi_fuel_yoy,wpi_manufacturing_yoy
158,2026-03-01,NaN,104.6,93.5,104.7,111.4,3.976143,2.578269,3.200883,4.804805
159,2026-04-01,NaN,108.9,111.0,107.0,112.8,8.358209,3.963134,25.000000,6.679960
160,2026-05-01,NaN,110.1,113.4,108.0,114.0,9.880240,5.263158,30.795848,7.676969
161,2026-06-01,NaN,110.2,111.1,107.8,116.1,9.870389,7.004608,27.408257,7.477567
162,2026-07-01,NaN,110.0,105.4,108.4,117.2,9.780439,8.518519,20.045558,8.291708

In [57]:
print("Start:", master_long["date"].min())
print("End:", master_long["date"].max())
print("Rows:", len(master_long))

Start: 2013-01-01 00:00:00
End: 2026-07-01 00:00:00
Rows: 163

In [58]:
master_long.isna().sum()

date                       0
cpi_combined               7
wpi_all                  123
wpi_fuel                 123
wpi_manufacturing        123
wpi_primary              123
wpi_all_yoy              135
wpi_primary_yoy          135
wpi_fuel_yoy             135
wpi_manufacturing_yoy    135
dtype: int64

In [59]:
master_all = pd.merge(
    master_long,
    ppi_master,
    on="date",
    how="outer"
)

master_all = (
    master_all
    .sort_values("date")
    .reset_index(drop=True)
)

display(master_all.head())
display(master_all.tail())

,date,cpi_combined,wpi_all,wpi_fuel,wpi_manufacturing,wpi_primary,wpi_all_yoy,wpi_primary_yoy,wpi_fuel_yoy,wpi_manufacturing_yoy,output_ppi,output_ppi_yoy
0,2013-01-01,104.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2013-02-01,105.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2013-03-01,105.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2013-04-01,106.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2013-05-01,106.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,date,cpi_combined,wpi_all,wpi_fuel,wpi_manufacturing,wpi_primary,wpi_all_yoy,wpi_primary_yoy,wpi_fuel_yoy,wpi_manufacturing_yoy,output_ppi,output_ppi_yoy
158,2026-03-01,NaN,104.6,93.5,104.7,111.4,3.976143,2.578269,3.200883,4.804805,104.9,4.170804
159,2026-04-01,NaN,108.9,111.0,107.0,112.8,8.358209,3.963134,25.000000,6.679960,108.8,8.258706
160,2026-05-01,NaN,110.1,113.4,108.0,114.0,9.880240,5.263158,30.795848,7.676969,109.9,9.680639
161,2026-06-01,NaN,110.2,111.1,107.8,116.1,9.870389,7.004608,27.408257,7.477567,109.9,9.571286
162,2026-07-01,NaN,110.0,105.4,108.4,117.2,9.780439,8.518519,20.045558,8.291708,109.9,9.571286

In [60]:
print("Shape:", master_all.shape)

print("\nColumns:")
print(master_all.columns.tolist())

Shape: (163, 12)

Columns:
['date', 'cpi_combined', 'wpi_all', 'wpi_fuel', 'wpi_manufacturing', 'wpi_primary', 'wpi_all_yoy', 'wpi_primary_yoy', 'wpi_fuel_yoy', 'wpi_manufacturing_yoy', 'output_ppi', 'output_ppi_yoy']

In [61]:
display(cpi_rural.head())
display(cpi_urban.head())
display(cpi_food.head())

         date  cpi_rural
18 2025-01-01     101.81
17 2025-02-01     101.33
16 2025-03-01     101.34
15 2025-04-01     101.49
14 2025-05-01     101.78

         date  cpi_urban
18 2025-01-01     101.49
17 2025-02-01     101.30
16 2025-03-01     101.47
15 2025-04-01     101.71
14 2025-05-01     102.06

,base_year,month_code,series,year,month,state,sector,division,group,class,sub_class,item,code,weight,index,inflation,imputation,value
0,2024,7,Current,2026,July,All India,Rural,CPI (General),NaN,NaN,NaN,NaN,NaN,55.419206,108.34,4.84,NaN,108.34
1,2024,6,Current,2026,June,All India,Rural,CPI (General),NaN,NaN,NaN,NaN,NaN,55.419206,107.24,4.74,NaN,107.24
2,2024,5,Current,2026,May,All India,Rural,CPI (General),NaN,NaN,NaN,NaN,NaN,55.419206,106.11,4.25,NaN,106.11
3,2024,4,Current,2026,April,All India,Rural,CPI (General),NaN,NaN,NaN,NaN,NaN,55.419206,105.28,3.74,NaN,105.28
4,2024,3,Current,2026,March,All India,Rural,CPI (General),NaN,NaN,NaN,NaN,NaN,55.419206,105.02,3.63,NaN,105.02

In [62]:
master_all = pd.merge(
    master_all,
    cpi_rural[["date", "cpi_rural"]],
    on="date",
    how="outer"
)

In [63]:
master_all = pd.merge(
    master_all,
    cpi_urban[["date", "cpi_urban"]],
    on="date",
    how="outer"
)

In [65]:
print(cpi_food.columns.tolist())

['base_year', 'month_code', 'series', 'year', 'month', 'state', 'sector', 'division', 'group', 'class', 'sub_class', 'item', 'code', 'weight', 'index', 'inflation', 'imputation', 'value']

In [69]:
import pandas as pd

# Load the Food CPI file again
cpi_food = pd.read_csv(
    r"C:\Users\Adity\OneDrive\Desktop\RESEARCH\Project Work\Inflation-Forecasting-Dashboard\cpi_rural_current_2024base.csv"
)

# Check what was loaded
print("Original columns:")
print(cpi_food.columns.tolist())

# Create a proper monthly date
cpi_food["date"] = pd.to_datetime(
    cpi_food["year"].astype(str)
    + "-"
    + cpi_food["month_code"].astype(str)
    + "-01"
)

# Keep only the fields we need and rename the index
cpi_food = (
    cpi_food[
        ["date", "index"]
    ]
    .rename(columns={"index": "cpi_rural_food"})
    .sort_values("date")
    .reset_index(drop=True)
)

print("\nFinal columns:")
print(cpi_food.columns.tolist())

display(cpi_food.head())
display(cpi_food.tail())

Original columns:
['base_year', 'month_code', 'series', 'year', 'month', 'state', 'sector', 'division', 'group', 'class', 'sub_class', 'item', 'code', 'weight', 'index', 'inflation', 'imputation', 'value']

Final columns:
['date', 'cpi_rural_food']

        date  cpi_rural_food
0 2025-01-01          101.81
1 2025-02-01          101.33
2 2025-03-01          101.34
3 2025-04-01          101.49
4 2025-05-01          101.78

         date  cpi_rural_food
14 2026-03-01          105.02
15 2026-04-01          105.28
16 2026-05-01          106.11
17 2026-06-01          107.24
18 2026-07-01          108.34

In [71]:
master_all = pd.merge(
    master_all,
    cpi_food,
    on="date",
    how="outer"
)

master_all = (
    master_all
    .sort_values("date")
    .reset_index(drop=True)
)

display(master_all.head())
display(master_all.tail())

,date,cpi_combined,wpi_all,wpi_fuel,wpi_manufacturing,wpi_primary,wpi_all_yoy,wpi_primary_yoy,wpi_fuel_yoy,wpi_manufacturing_yoy,output_ppi,output_ppi_yoy,cpi_rural,cpi_urban,cpi_rural_food_x,cpi_rural_food_y
0,2013-01-01,104.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2013-02-01,105.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2013-03-01,105.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2013-04-01,106.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2013-05-01,106.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,date,cpi_combined,wpi_all,wpi_fuel,wpi_manufacturing,wpi_primary,wpi_all_yoy,wpi_primary_yoy,wpi_fuel_yoy,wpi_manufacturing_yoy,output_ppi,output_ppi_yoy,cpi_rural,cpi_urban,cpi_rural_food_x,cpi_rural_food_y
158,2026-03-01,NaN,104.6,93.5,104.7,111.4,3.976143,2.578269,3.200883,4.804805,104.9,4.170804,105.02,104.62,105.02,105.02
159,2026-04-01,NaN,108.9,111.0,107.0,112.8,8.358209,3.963134,25.000000,6.679960,108.8,8.258706,105.28,104.92,105.28,105.28
160,2026-05-01,NaN,110.1,113.4,108.0,114.0,9.880240,5.263158,30.795848,7.676969,109.9,9.680639,106.11,105.66,106.11,106.11
161,2026-06-01,NaN,110.2,111.1,107.8,116.1,9.870389,7.004608,27.408257,7.477567,109.9,9.571286,107.24,106.69,107.24,107.24
162,2026-07-01,NaN,110.0,105.4,108.4,117.2,9.780439,8.518519,20.045558,8.291708,109.9,9.571286,108.34,107.45,108.34,108.34

In [72]:
print("Shape:", master_all.shape)

print("\nMissing values:")
print(master_all.isna().sum())

print("\nDuplicate dates:",
      master_all["date"].duplicated().sum())

Shape: (163, 16)

Missing values:
date                       0
cpi_combined               7
wpi_all                  123
wpi_fuel                 123
wpi_manufacturing        123
wpi_primary              123
wpi_all_yoy              135
wpi_primary_yoy          135
wpi_fuel_yoy             135
wpi_manufacturing_yoy    135
output_ppi               123
output_ppi_yoy           135
cpi_rural                144
cpi_urban                144
cpi_rural_food_x         144
cpi_rural_food_y         144
dtype: int64

Duplicate dates: 0

In [77]:
print("========== MASTER DATASET AUDIT ==========")

print("Rows:", len(master_all))
print("Columns:", len(master_all.columns))

print(
    "Date range:",
    master_all["date"].min(),
    "to",
    master_all["date"].max()
)

print(
    "Duplicate dates:",
    master_all["date"].duplicated().sum()
)

print(
    "Missing CPI:",
    master_all["cpi_combined"].isna().sum()
)

print(
    "Missing WPI:",
    master_all["wpi_all"].isna().sum()
)

print(
    "Missing PPI:",
    master_all["output_ppi"].isna().sum()
)

print("==========================================")

========== MASTER DATASET AUDIT ==========
Rows: 163
Columns: 16
Date range: 2013-01-01 00:00:00 to 2026-07-01 00:00:00
Duplicate dates: 0
Missing CPI: 7
Missing WPI: 123
Missing PPI: 123
==========================================

In [76]:
master_all.to_csv(
    PROCESSED / "master_monthly_dataset.csv",
    index=False
)
print(
    "Saved to:",
    PROCESSED / "master_monthly_dataset.csv"
)

Saved to: C:\Users\Adity\OneDrive\Desktop\RESEARCH\Project Work\Inflation-Forecasting-Dashboard\data\processed\master_monthly_dataset.csv

In [80]:
print([name for name in globals() if name in [
    "cpi_hist",
    "cpi_rural",
    "cpi_urban",
    "cpi_food",
    "wpi_master",
    "ppi_master",
    "master_all",
    "model_data"
]])

['cpi_hist', 'cpi_rural', 'cpi_urban', 'cpi_food', 'wpi_master', 'ppi_master', 'master_all']

In [83]:
print("MASTER_ALL COLUMNS:")
print(master_all.columns.tolist())

MASTER_ALL COLUMNS:
['date', 'cpi_combined', 'wpi_all', 'wpi_fuel', 'wpi_manufacturing', 'wpi_primary', 'wpi_all_yoy', 'wpi_primary_yoy', 'wpi_fuel_yoy', 'wpi_manufacturing_yoy', 'output_ppi', 'output_ppi_yoy', 'cpi_rural', 'cpi_urban', 'cpi_rural_food_x', 'cpi_rural_food_y']

In [85]:
required_columns = [
    "date",
    "cpi_combined",
    "cpi_yoy",
    "wpi_all",
    "wpi_primary",
    "wpi_fuel",
    "wpi_manufacturing",
    "wpi_all_yoy",
    "wpi_primary_yoy",
    "wpi_fuel_yoy",
    "wpi_manufacturing_yoy",
    "output_ppi",
    "output_ppi_yoy"
]

missing_columns = [
    col for col in required_columns
    if col not in master_all.columns
]

print("Missing columns:")
print(missing_columns)

Missing columns:
['cpi_yoy']

In [86]:
print(master_all.head())
print(master_all.columns.tolist())

        date  cpi_combined  wpi_all  wpi_fuel  wpi_manufacturing  wpi_primary  \
0 2013-01-01         104.6      NaN       NaN                NaN          NaN
1 2013-02-01         105.3      NaN       NaN                NaN          NaN
2 2013-03-01         105.5      NaN       NaN                NaN          NaN
3 2013-04-01         106.1      NaN       NaN                NaN          NaN
4 2013-05-01         106.9      NaN       NaN                NaN          NaN

   wpi_all_yoy  wpi_primary_yoy  wpi_fuel_yoy  wpi_manufacturing_yoy  \
0          NaN              NaN           NaN                    NaN
1          NaN              NaN           NaN                    NaN
2          NaN              NaN           NaN                    NaN
3          NaN              NaN           NaN                    NaN
4          NaN              NaN           NaN                    NaN

   output_ppi  output_ppi_yoy  cpi_rural  cpi_urban  cpi_rural_food_x  \
0         NaN             NaN        NaN        NaN               NaN
1         NaN             NaN        NaN        NaN               NaN
2         NaN             NaN        NaN        NaN               NaN
3         NaN             NaN        NaN        NaN               NaN
4         NaN             NaN        NaN        NaN               NaN

   cpi_rural_food_y
0               NaN
1               NaN
2               NaN
3               NaN
4               NaN
['date', 'cpi_combined', 'wpi_all', 'wpi_fuel', 'wpi_manufacturing', 'wpi_primary', 'wpi_all_yoy', 'wpi_primary_yoy', 'wpi_fuel_yoy', 'wpi_manufacturing_yoy', 'output_ppi', 'output_ppi_yoy', 'cpi_rural', 'cpi_urban', 'cpi_rural_food_x', 'cpi_rural_food_y']

In [88]:
master_all["cpi_yoy"] = (
    master_all["cpi_combined"]
    .pct_change(12)
    * 100
)
for column in [
    "wpi_all",
    "wpi_primary",
    "wpi_fuel",
    "wpi_manufacturing"
]:
    master_all[f"{column}_yoy"] = (
        master_all[column]
        .pct_change(12)
        * 100
    )
    master_all["output_ppi_yoy"] = (
    master_all["output_ppi"]
    .pct_change(12)
    * 100
)

C:\Users\Adity\AppData\Local\Temp\ipykernel_23968\1160303858.py:3: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  .pct_change(12)

In [89]:
print(master_all.columns.tolist())

['date', 'cpi_combined', 'wpi_all', 'wpi_fuel', 'wpi_manufacturing', 'wpi_primary', 'wpi_all_yoy', 'wpi_primary_yoy', 'wpi_fuel_yoy', 'wpi_manufacturing_yoy', 'output_ppi', 'output_ppi_yoy', 'cpi_rural', 'cpi_urban', 'cpi_rural_food_x', 'cpi_rural_food_y', 'cpi_yoy']

In [90]:
model_data = master_all[
    [
        "date",
        "cpi_combined",
        "cpi_yoy",
        "wpi_all",
        "wpi_primary",
        "wpi_fuel",
        "wpi_manufacturing",
        "wpi_all_yoy",
        "wpi_primary_yoy",
        "wpi_fuel_yoy",
        "wpi_manufacturing_yoy",
        "output_ppi",
        "output_ppi_yoy"
    ]
].copy()

print("model_data created successfully.")
print("Shape:", model_data.shape)

display(model_data.head())

model_data created successfully.
Shape: (163, 13)

,date,cpi_combined,cpi_yoy,wpi_all,wpi_primary,wpi_fuel,wpi_manufacturing,wpi_all_yoy,wpi_primary_yoy,wpi_fuel_yoy,wpi_manufacturing_yoy,output_ppi,output_ppi_yoy
0,2013-01-01,104.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2013-02-01,105.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2013-03-01,105.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2013-04-01,106.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2013-05-01,106.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [91]:
print(master_all.columns.tolist())

['date', 'cpi_combined', 'wpi_all', 'wpi_fuel', 'wpi_manufacturing', 'wpi_primary', 'wpi_all_yoy', 'wpi_primary_yoy', 'wpi_fuel_yoy', 'wpi_manufacturing_yoy', 'output_ppi', 'output_ppi_yoy', 'cpi_rural', 'cpi_urban', 'cpi_rural_food_x', 'cpi_rural_food_y', 'cpi_yoy']

In [92]:
required_columns = [
    "date",
    "cpi_combined",
    "cpi_yoy",
    "wpi_all",
    "wpi_primary",
    "wpi_fuel",
    "wpi_manufacturing",
    "wpi_all_yoy",
    "wpi_primary_yoy",
    "wpi_fuel_yoy",
    "wpi_manufacturing_yoy",
    "output_ppi",
    "output_ppi_yoy"
]

print([
    col for col in required_columns
    if col not in master_all.columns
])

[]

In [93]:
required_columns = [
    "date",
    "cpi_combined",
    "cpi_yoy",
    "wpi_all",
    "wpi_primary",
    "wpi_fuel",
    "wpi_manufacturing",
    "wpi_all_yoy",
    "wpi_primary_yoy",
    "wpi_fuel_yoy",
    "wpi_manufacturing_yoy",
    "output_ppi",
    "output_ppi_yoy"
]

model_data = master_all.loc[:, required_columns].copy()

print("model_data created successfully.")
print("Shape:", model_data.shape)

display(model_data.head())

model_data created successfully.
Shape: (163, 13)

,date,cpi_combined,cpi_yoy,wpi_all,wpi_primary,wpi_fuel,wpi_manufacturing,wpi_all_yoy,wpi_primary_yoy,wpi_fuel_yoy,wpi_manufacturing_yoy,output_ppi,output_ppi_yoy
0,2013-01-01,104.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2013-02-01,105.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2013-03-01,105.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2013-04-01,106.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2013-05-01,106.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [94]:
print("Columns:")
print(model_data.columns.tolist())

print("\nMissing values:")
print(model_data.isna().sum())

print("\nDuplicate dates:",
      model_data["date"].duplicated().sum())

Columns:
['date', 'cpi_combined', 'cpi_yoy', 'wpi_all', 'wpi_primary', 'wpi_fuel', 'wpi_manufacturing', 'wpi_all_yoy', 'wpi_primary_yoy', 'wpi_fuel_yoy', 'wpi_manufacturing_yoy', 'output_ppi', 'output_ppi_yoy']

Missing values:
date                       0
cpi_combined               7
cpi_yoy                   12
wpi_all                  123
wpi_primary              123
wpi_fuel                 123
wpi_manufacturing        123
wpi_all_yoy              135
wpi_primary_yoy          135
wpi_fuel_yoy             135
wpi_manufacturing_yoy    135
output_ppi               123
output_ppi_yoy           135
dtype: int64

Duplicate dates: 0

In [95]:
long_sample = model_data[
    model_data["cpi_yoy"].notna()
    & model_data["wpi_all_yoy"].notna()
].copy()

long_sample = (
    long_sample
    .sort_values("date")
    .reset_index(drop=True)
)

print("CPI + WPI sample:", long_sample.shape)
print(
    "Range:",
    long_sample["date"].min(),
    "to",
    long_sample["date"].max()
)

CPI + WPI sample: (28, 13)
Range: 2024-04-01 00:00:00 to 2026-07-01 00:00:00

In [96]:
ppi_sample = model_data[
    model_data["cpi_yoy"].notna()
    & model_data["wpi_all_yoy"].notna()
    & model_data["output_ppi_yoy"].notna()
].copy()

ppi_sample = (
    ppi_sample
    .sort_values("date")
    .reset_index(drop=True)
)

print("CPI + WPI + PPI sample:", ppi_sample.shape)
print(
    "Range:",
    ppi_sample["date"].min(),
    "to",
    ppi_sample["date"].max()
)

CPI + WPI + PPI sample: (28, 13)
Range: 2024-04-01 00:00:00 to 2026-07-01 00:00:00

In [97]:
long_sample.to_csv(
    PROCESSED / "model_sample_cpi_wpi.csv",
    index=False
)

ppi_sample.to_csv(
    PROCESSED / "model_sample_cpi_wpi_ppi.csv",
    index=False
)

print("Both model samples saved successfully.")

Both model samples saved successfully.