In [1]:
import pandas as pd
from pathlib import Path

PROCESSED = Path(
    r"C:\Users\Adity\OneDrive\Desktop\RESEARCH\Project Work\Inflation-Forecasting-Dashboard\data\processed"
)

In [2]:
cpi_long = pd.read_csv(
    PROCESSED / "cpi_long_model.csv"
)

cpi_long["date"] = pd.to_datetime(
    cpi_long["date"],
    format="%d-%m-%Y"
)

cpi_long = (
    cpi_long
    .sort_values("date")
    .reset_index(drop=True)
)

print(
    "CPI Long:",
    cpi_long["date"].min(),
    "→",
    cpi_long["date"].max()
)

display(cpi_long.head())
display(cpi_long.tail())

CPI Long: 2013-01-01 00:00:00 → 2025-12-01 00:00:00

        date  cpi_combined  cpi_yoy
0 2013-01-01         104.6      NaN
1 2013-02-01         105.3      NaN
2 2013-03-01         105.5      NaN
3 2013-04-01         106.1      NaN
4 2013-05-01         106.9      NaN

          date  cpi_combined   cpi_yoy
151 2025-08-01         197.0  2.072539
152 2025-09-01         197.0  1.441813
153 2025-10-01         197.3  0.254065
154 2025-11-01         197.9  0.712468
155 2025-12-01         198.0  1.330604

In [3]:
cpi_wpi = pd.read_csv(
    PROCESSED / "cpi_wpi_common_model.csv"
)

cpi_wpi["date"] = pd.to_datetime(
    cpi_wpi["date"],
    format="%d-%m-%Y"
)

cpi_wpi = (
    cpi_wpi
    .sort_values("date")
    .reset_index(drop=True)
)

print(
    "CPI + WPI:",
    cpi_wpi["date"].min(),
    "→",
    cpi_wpi["date"].max()
)

display(cpi_wpi.head())
display(cpi_wpi.tail())

CPI + WPI: 2024-04-01 00:00:00 → 2025-12-01 00:00:00

,date,cpi_combined,cpi_yoy,wpi_all,wpi_fuel,wpi_manufacturing,wpi_primary,wpi_all_yoy,wpi_primary_yoy,wpi_fuel_yoy,wpi_manufacturing_yoy,output_ppi,output_ppi_yoy
0,2024-04-01,186.7,4.828748,99.9,92.0,98.5,108.8,0.909091,6.666667,-2.127660,-0.605449,99.7,0.605449
1,2024-05-01,187.7,4.801787,100.4,91.7,98.9,110.1,1.825558,7.624633,0.328228,0.000000,100.1,1.521298
2,2024-06-01,190.2,5.082873,100.7,89.9,99.1,111.8,2.441506,8.228461,-0.662983,0.916497,100.4,2.240326
3,2024-07-01,193.0,3.596350,101.0,91.2,98.8,113.1,1.917255,4.819277,0.662252,1.022495,100.8,1.715439
4,2024-08-01,193.0,3.651987,100.8,90.9,98.4,113.8,1.306533,5.370370,-0.980392,0.305810,100.7,1.307847

,date,cpi_combined,cpi_yoy,wpi_all,wpi_fuel,wpi_manufacturing,wpi_primary,wpi_all_yoy,wpi_primary_yoy,wpi_fuel_yoy,wpi_manufacturing_yoy,output_ppi,output_ppi_yoy
16,2025-08-01,197.0,2.072539,100.8,88.1,100.4,109.6,0.000000,-3.690685,-3.080308,2.032520,100.9,0.198610
17,2025-09-01,197.0,1.441813,101.0,87.8,100.4,110.7,-0.197628,-4.072790,-2.552719,1.825558,101.0,0.000000
18,2025-10-01,197.3,0.254065,100.9,87.1,100.6,110.4,-1.175318,-5.721605,-3.863135,1.411290,101.1,-0.687623
19,2025-11-01,197.9,0.712468,101.5,88.4,100.6,112.3,-0.587659,-4.099061,-2.963776,1.411290,101.7,-0.294118
20,2025-12-01,198.0,1.330604,101.9,89.0,101.1,112.0,0.295276,-2.777778,-2.625821,2.224469,102.1,0.591133

In [4]:
cpi_wpi_ppi = pd.read_csv(
    PROCESSED / "cpi_wpi_ppi_common_model.csv"
)

cpi_wpi_ppi["date"] = pd.to_datetime(
    cpi_wpi_ppi["date"],
    format="%d-%m-%Y"
)

cpi_wpi_ppi = (
    cpi_wpi_ppi
    .sort_values("date")
    .reset_index(drop=True)
)

print(
    "CPI + WPI + PPI:",
    cpi_wpi_ppi["date"].min(),
    "→",
    cpi_wpi_ppi["date"].max()
)

display(cpi_wpi_ppi.head())
display(cpi_wpi_ppi.tail())

CPI + WPI + PPI: 2024-04-01 00:00:00 → 2025-12-01 00:00:00

,date,cpi_combined,cpi_yoy,wpi_all,wpi_fuel,wpi_manufacturing,wpi_primary,wpi_all_yoy,wpi_primary_yoy,wpi_fuel_yoy,wpi_manufacturing_yoy,output_ppi,output_ppi_yoy
0,2024-04-01,186.7,4.828748,99.9,92.0,98.5,108.8,0.909091,6.666667,-2.127660,-0.605449,99.7,0.605449
1,2024-05-01,187.7,4.801787,100.4,91.7,98.9,110.1,1.825558,7.624633,0.328228,0.000000,100.1,1.521298
2,2024-06-01,190.2,5.082873,100.7,89.9,99.1,111.8,2.441506,8.228461,-0.662983,0.916497,100.4,2.240326
3,2024-07-01,193.0,3.596350,101.0,91.2,98.8,113.1,1.917255,4.819277,0.662252,1.022495,100.8,1.715439
4,2024-08-01,193.0,3.651987,100.8,90.9,98.4,113.8,1.306533,5.370370,-0.980392,0.305810,100.7,1.307847

,date,cpi_combined,cpi_yoy,wpi_all,wpi_fuel,wpi_manufacturing,wpi_primary,wpi_all_yoy,wpi_primary_yoy,wpi_fuel_yoy,wpi_manufacturing_yoy,output_ppi,output_ppi_yoy
16,2025-08-01,197.0,2.072539,100.8,88.1,100.4,109.6,0.000000,-3.690685,-3.080308,2.032520,100.9,0.198610
17,2025-09-01,197.0,1.441813,101.0,87.8,100.4,110.7,-0.197628,-4.072790,-2.552719,1.825558,101.0,0.000000
18,2025-10-01,197.3,0.254065,100.9,87.1,100.6,110.4,-1.175318,-5.721605,-3.863135,1.411290,101.1,-0.687623
19,2025-11-01,197.9,0.712468,101.5,88.4,100.6,112.3,-0.587659,-4.099061,-2.963776,1.411290,101.7,-0.294118
20,2025-12-01,198.0,1.330604,101.9,89.0,101.1,112.0,0.295276,-2.777778,-2.625821,2.224469,102.1,0.591133

In [5]:
print("========== DATE VALIDATION ==========")

for name, df in {
    "CPI Long": cpi_long,
    "CPI + WPI": cpi_wpi,
    "CPI + WPI + PPI": cpi_wpi_ppi
}.items():

    expected = pd.date_range(
        start=df["date"].min(),
        end=df["date"].max(),
        freq="MS"
    )

    missing = expected.difference(df["date"])

    print(f"\n{name}")
    print("Start:", df["date"].min())
    print("End:", df["date"].max())
    print("Rows:", len(df))
    print("Duplicate dates:", df["date"].duplicated().sum())
    print("Missing calendar months:", len(missing))

print("\n=====================================")

========== DATE VALIDATION ==========

CPI Long
Start: 2013-01-01 00:00:00
End: 2025-12-01 00:00:00
Rows: 156
Duplicate dates: 0
Missing calendar months: 0

CPI + WPI
Start: 2024-04-01 00:00:00
End: 2025-12-01 00:00:00
Rows: 21
Duplicate dates: 0
Missing calendar months: 0

CPI + WPI + PPI
Start: 2024-04-01 00:00:00
End: 2025-12-01 00:00:00
Rows: 21
Duplicate dates: 0
Missing calendar months: 0

=====================================

In [6]:
cpi_long.to_csv(
    PROCESSED / "cpi_long_model.csv",
    index=False
)

cpi_wpi.to_csv(
    PROCESSED / "cpi_wpi_common_model.csv",
    index=False
)

cpi_wpi_ppi.to_csv(
    PROCESSED / "cpi_wpi_ppi_common_model.csv",
    index=False
)

print("Corrected model datasets saved successfully.")

Corrected model datasets saved successfully.

In [7]:
check_long = pd.read_csv(
    PROCESSED / "cpi_long_model.csv",
    parse_dates=["date"],
    dayfirst=True
)

check_wpi = pd.read_csv(
    PROCESSED / "cpi_wpi_common_model.csv",
    parse_dates=["date"],
    dayfirst=True
)

check_ppi = pd.read_csv(
    PROCESSED / "cpi_wpi_ppi_common_model.csv",
    parse_dates=["date"],
    dayfirst=True
)

print(
    check_long["date"].min(),
    "→",
    check_long["date"].max()
)

print(
    check_wpi["date"].min(),
    "→",
    check_wpi["date"].max()
)

print(
    check_ppi["date"].min(),
    "→",
    check_ppi["date"].max()
)

2013-01-01 00:00:00 → 2025-01-12 00:00:00
2024-01-04 00:00:00 → 2025-01-12 00:00:00
2024-01-04 00:00:00 → 2025-01-12 00:00:00

In [8]:
df["date"] = pd.to_datetime(
    df["date"],
    format="%d-%m-%Y"
)

In [9]:
from pathlib import Path
import pandas as pd

PROCESSED = Path(
    r"C:\Users\Adity\OneDrive\Desktop\RESEARCH\Project Work\Inflation-Forecasting-Dashboard\data\processed"
)

print("Processed folder:")
print(PROCESSED)

print("\nFolder exists:", PROCESSED.exists())

print("\nFiles currently in processed:")
for f in PROCESSED.iterdir():
    print(f.name)

Processed folder:
C:\Users\Adity\OneDrive\Desktop\RESEARCH\Project Work\Inflation-Forecasting-Dashboard\data\processed

Folder exists: True

Files currently in processed:
cpi_long_model.csv
cpi_wpi_common_model.csv
cpi_wpi_ppi_common_model.csv

In [10]:
# Save corrected CPI long dataset
cpi_long.to_csv(
    PROCESSED / "cpi_long_model.csv",
    index=False
)

# Save corrected CPI + WPI dataset
cpi_wpi.to_csv(
    PROCESSED / "cpi_wpi_common_model.csv",
    index=False
)

# Save corrected CPI + WPI + PPI dataset
cpi_wpi_ppi.to_csv(
    PROCESSED / "cpi_wpi_ppi_common_model.csv",
    index=False
)

print("All three files saved.")

All three files saved.

In [11]:
files_to_check = [
    "cpi_long_model.csv",
    "cpi_wpi_common_model.csv",
    "cpi_wpi_ppi_common_model.csv"
]

for filename in files_to_check:
    path = PROCESSED / filename
    
    print(
        filename,
        "→",
        "EXISTS" if path.exists() else "NOT FOUND"
    )

cpi_long_model.csv → EXISTS
cpi_wpi_common_model.csv → EXISTS
cpi_wpi_ppi_common_model.csv → EXISTS

In [12]:
for filename in files_to_check:
    path = PROCESSED / filename
    
    df_check = pd.read_csv(path)
    
    print("\n", filename)
    print("Rows:", len(df_check))
    print("Columns:", df_check.columns.tolist())
    print(
        "Date values:",
        df_check["date"].iloc[0],
        "→",
        df_check["date"].iloc[-1]
    )

 cpi_long_model.csv
Rows: 156
Columns: ['date', 'cpi_combined', 'cpi_yoy']
Date values: 2013-01-01 → 2025-12-01

 cpi_wpi_common_model.csv
Rows: 21
Columns: ['date', 'cpi_combined', 'cpi_yoy', 'wpi_all', 'wpi_fuel', 'wpi_manufacturing', 'wpi_primary', 'wpi_all_yoy', 'wpi_primary_yoy', 'wpi_fuel_yoy', 'wpi_manufacturing_yoy', 'output_ppi', 'output_ppi_yoy']
Date values: 2024-04-01 → 2025-12-01

 cpi_wpi_ppi_common_model.csv
Rows: 21
Columns: ['date', 'cpi_combined', 'cpi_yoy', 'wpi_all', 'wpi_fuel', 'wpi_manufacturing', 'wpi_primary', 'wpi_all_yoy', 'wpi_primary_yoy', 'wpi_fuel_yoy', 'wpi_manufacturing_yoy', 'output_ppi', 'output_ppi_yoy']
Date values: 2024-04-01 → 2025-12-01